# Generated by Django 3.2.7 on 2021-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_fname', models.CharField(max_length=20)),
                ('contact_lname', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.CharField(max_length=30)),
            ],
        ),
    ]
